// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp.GenerateVariable;
using Microsoft.CodeAnalysis.Test.Utilities;
using Roslyn.Test.Utilities;
using Xunit;

namespace Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.GenerateVariable;

public sealed partial class GenerateVariableTests
{
    private sealed record RazorGeneratedDocumentData(string HintName, string GeneratedCode);

    protected override void InitializeWorkspace(TestWorkspace workspace, TestParameters parameters)
    {
        if (parameters.fixProviderData is not RazorGeneratedDocumentData generatedDocument)
        {
            return;
        }

        var project = workspace.CurrentSolution.Projects.Single();
        var updatedProject = project.AddAnalyzerReference(
            new TestGeneratorReference(
                new Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator(
                    context => context.AddSource(generatedDocument.HintName, generatedDocument.GeneratedCode))));

        Assert.True(workspace.TryApplyChanges(updatedProject.Solution));
    }

    private static TestParameters WithRazorGeneratedDocument(string generatedCode, string hintName = "Component.razor.g.cs")
        => new(fixProviderData: new RazorGeneratedDocumentData(hintName, generatedCode));

    private async Task TestGenerateFieldOrPropertyNotOfferedIntoRazorSourceGeneratedDocumentAsync(
        string workspaceMarkup,
        string generatedCode,
        bool requestFromSourceGeneratedDocument)
    {
        using var workspace = CreateWorkspaceFromOptions(
            workspaceMarkup,
            WithRazorGeneratedDocument(generatedCode));

        var project = workspace.CurrentSolution.Projects.Single();
        var sourceGeneratedDocument = Assert.Single(await project.GetSourceGeneratedDocumentsAsync(CancellationToken.None));
        var requestDocument = requestFromSourceGeneratedDocument
            ? sourceGeneratedDocument
            : project.Documents.Single();
        var requestTree = await requestDocument.GetSyntaxTreeAsync(CancellationToken.None);
        var compilation = await project.GetCompilationAsync(CancellationToken.None);

        Assert.NotNull(requestTree);
        Assert.NotNull(compilation);

        var diagnostic = Assert.Single(
            compilation!.GetDiagnostics(CancellationToken.None).Where(
                diagnostic => diagnostic.Severity == DiagnosticSeverity.Error && diagnostic.Location.SourceTree == requestTree));

        var codeActions = new List<CodeAction>();
        var context = new CodeFixContext(
            requestDocument,
            diagnostic.Location.SourceSpan,
            [diagnostic],
            (action, _) => codeActions.Add(action),
            CancellationToken.None);

        var provider = new CSharpGenerateVariableCodeFixProvider();
        await provider.RegisterCodeFixesAsync(context);

        Assert.Empty(codeActions);
    }

    [Fact]
    public Task TestGenerateFieldOrPropertyNotOfferedIntoRazorSourceGeneratedDocumentFromRegularDocument()
        => TestGenerateFieldOrPropertyNotOfferedIntoRazorSourceGeneratedDocumentAsync(
            """
            <Workspace>
                <Project Language="C#" AssemblyName="ClassLibrary1" CommonReferences="true">
                    <Document>
            public class C
            {
                public object M() => Component.Mi$$ssing;
            }
                    </Document>
                </Project>
            </Workspace>
            """,
            """
            // <auto-generated />

            public partial class Component
            {
            }
            """,
            requestFromSourceGeneratedDocument: false);

    [Fact]
    public Task TestGenerateFieldOrPropertyNotOfferedIntoRazorSourceGeneratedDocument()
        => TestGenerateFieldOrPropertyNotOfferedIntoRazorSourceGeneratedDocumentAsync(
            """
            <Workspace>
                <Project Language="C#" AssemblyName="ClassLibrary1" CommonReferences="true">
                    <Document>
            public class Placeholder
            {
            }
                    </Document>
                </Project>
            </Workspace>
            """,
            """
            // <auto-generated />

            public partial class Component
            {
                public object M() => this.Missing;
            }
            """,
            requestFromSourceGeneratedDocument: true);
}
